apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: kk-test
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080  # Assuming your application is listening on port 8080
    protocol: TCP
  selector:
    app: hello-world
