apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-disk-pvc
  namespace: kk-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-csi

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-disk-deployment
  namespace: kk-test
  labels:
    app: azure-disk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-disk-app
  template:
    metadata:
      labels:
        app: azure-disk-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: azure-disk-volume
          mountPath: /mnt/azuredisk
      volumes:
      - name: azure-disk-volume
        persistentVolumeClaim:
          claimName: azure-disk-pvc