apiVersion: v1
kind: Pod
metadata:
  name: my-local-pod
spec:
  containers:
  - name: my-app
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-local-pvc

