apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-image
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-image
  template:
    metadata:
      labels:
        app: my-image
    spec:
      containers:
      - name: my-image-kk-hub
        image: hub4kishore/my-image
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 800m