apiVersion: apps/v1  # Older versions of k8s use apps/v1beta1
kind: Deployment
metadata:
 name: hello-deploy
 namespace: kk-test
spec:
 replicas: 10
 selector:
   matchLabels:
     app: hello-world
 minReadySeconds: 10
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
     maxSurge: 1
 template:
   metadata:
     labels:
       app: hello-world
   spec:
     containers:
     - name: hello-pod
       image: nigelpoulton/k8sbook:latest
       ports:
       - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: kk-test
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080  # Assuming your application is listening on port 8080
    protocol: TCP
  selector:
    app: hello-world
