apiVersion: v1
kind: Deployment
metadata:
  name: test yml

spec:
  selector:
    matchLabels:
      app: test
  
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        name: test image
        image: hub4kishore/my-image
        ports:
          containerPort: 3000
