apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kk-role
rules:
- apiGroups: [""]
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  verbs: ["get", "watch", "list","create"]
  resources: ["pods", "pods/log","pods/exec"]