
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kk-role-binding
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kk
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: test-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kk-role