apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: kk-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: my-app-container
          image: klentytest.azurecr.io/kksample:latest
          command: ["sleep", "120"]
