apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}  # Temporary shared storage between containers

  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
      ports:
        - containerPort: 80

    - name: sidecar-logger
      image: busybox
      command: ["/bin/sh", "-c", "while true; do cat /var/log/nginx/access.log; sleep 5; done"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
