# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kk-deployment
  namespace: kk-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: klentytest.azurecr.io/kksample:latest
        envFrom:
        - secretRef:
            name: my-secret
        - configMapRef:
            name: my-configmap
        # env:
        # - name: PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: my-secret
        #       key: PASSWORD
