apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
  namespace: kk-test
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 4001
